// This file was generated by Prisma
import "dotenv/config";

// @ts-expect-error - يتم تجاهل هذا الخطأ لأن مترجم Next.js لا يتعرف على أنواع إعدادات Prisma
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
